# Generated by Django 5.2.5 on 2025-09-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('setor', models.CharField(max_length=12)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('média', 'Média'), ('alta', 'Alta')], max_length=6)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a fazer', 'A fazer'), ('fazendo', 'Fazendo'), ('pronto', 'Pronto')], default='fazer', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='api.usuario')),
            ],
        ),
    ]
