# Generated by Django 5.2.5 on 2025-09-17 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tarefa_data_cadastro_alter_tarefa_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
